import type { Cat, GameState, StockShare } from '@/types/game';
import { initStock } from './stocks';
import { INITIAL_LOAN } from './loan';
import { REPAY_INTERVAL } from './loanDeadline';

const INITIAL_MONEY = 100;
const INITIAL_PRICE = 10;
const PLAYER_INITIAL_CASH = 1000;

export const INITIAL_CATS: Cat[] = [
  {
    id: '1',
    name: 'シロ',
    personality: 'aggressive',
    job: 'investor',
    money: INITIAL_MONEY,
    hunger: 30,
    energy: 90,
    inventory: 0,
    action: 'idle',
    x: 20,
    y: 30,
    ambition: 0.8,
    company: null,
  },
  {
    id: '2',
    name: 'クロ',
    personality: 'conservative',
    job: 'producer',
    money: INITIAL_MONEY,
    hunger: 40,
    energy: 80,
    inventory: 1,
    action: 'idle',
    x: 55,
    y: 25,
    ambition: 0.3,
    company: null,
  },
  {
    id: '3',
    name: 'タマ',
    personality: 'lazy',
    job: 'producer',
    money: INITIAL_MONEY,
    hunger: 50,
    energy: 70,
    inventory: 1,
    action: 'idle',
    x: 75,
    y: 50,
    ambition: 0.2,
    company: null,
  },
  {
    id: '4',
    name: 'ミケ',
    personality: 'conservative',
    job: 'trader',
    money: INITIAL_MONEY,
    hunger: 35,
    energy: 85,
    inventory: 0,
    action: 'idle',
    x: 35,
    y: 60,
    ambition: 0.45,
    company: null,
  },
  {
    id: '5',
    name: 'チャトラ',
    personality: 'aggressive',
    job: 'trader',
    money: INITIAL_MONEY,
    hunger: 45,
    energy: 75,
    inventory: 0,
    action: 'idle',
    x: 60,
    y: 70,
    ambition: 0.7,
    company: null,
  },
];

export const INITIAL_STATE: GameState = {
  tick: 0,
  cats: INITIAL_CATS,
  market: {
    soupPrice: INITIAL_PRICE,
    supply: 0,
    demand: 0,
  },
  economy: {
    soupPrice: INITIAL_PRICE,
    inflationRate: 0,
    unemploymentRate: 0,
    gini: 0,
    totalMoney: INITIAL_CATS.length * INITIAL_MONEY,
    inflationHistory: [],
  },
  policy: {
    interestRate: 5,
    taxRate: 10,
  },
  newsLog: [],
  stocks: Object.fromEntries(
    INITIAL_CATS.map((c): [string, StockShare] => [c.id, initStock(c.money)]),
  ),
  player: {
    cash: PLAYER_INITIAL_CASH,
    holdings: {},
    costBasis: {},
    hasEverInvested: false,
    loan: INITIAL_LOAN,
  },
  weather: { current: 'normal', lockUntil: 0 },
  strike: { active: false, reliefCount: 0, startTick: 0, cooldownUntil: 0 },
  facilities: { soupFactory: 0, matatabiPark: 0, fishingPond: 0 },
  placements: [],
  missions: { index: 0, lastRewardTick: -1 },
  repayDueTick: REPAY_INTERVAL,
  gameOver: false,
  bubbles: {},
};
